# Generated by Django 5.0.6 on 2024-07-08 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='stub',
            field=models.CharField(default='', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
