# Generated by Django 5.0.6 on 2024-07-09 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_localactor_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='stub',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
