# Generated by Django 5.0.6 on 2024-07-13 09:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_note_stub'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('filepath', models.TextField(max_length=200)),
                ('thumbnail_path', models.TextField(max_length=200)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='Blog.note')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachment', to='Blog.localactor')),
            ],
        ),
    ]
