# Generated by Django 5.0.6 on 2024-07-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_remove_attachment_filepath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='image',
            field=models.ImageField(null=True, upload_to='media/attachments'),
        ),
    ]
