# Generated by Django 5.0.6 on 2024-07-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_attachment_focus_alter_attachment_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='focus_x',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attachment',
            name='focus_y',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
